name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/renehezser/readenergymeter:${{ github.run_number }}

    - name: Tag image with ubuntu-latest
      run: docker tag ghcr.io/renehezser/readenergymeter:${{ github.run_number }} ghcr.io/renehezser/readenergymeter:latest

    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Username used to log against the Docker registry
        username: ReneHezser
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.GHCRPAT }}
        # Log out from the Docker registry at the end of a job
        logout: true
    
    - name: Docker push
      run: docker push ghcr.io/renehezser/readenergymeter:${{ github.run_number }}
